### ISSUE TITLE
Reinitiate SSM Parameterstore CodeBuild Role keys

### ISSUE THREAD

**Issue by smjmoj** [ministryofjustice/staff-device-shared-services-infrastructure#79]
### User Story

As an engineer
I need to store the ARN of the "SharedServicesCodeBuild" role in SSM ParemeterStore with a project and environment specific key name 
So that
The value can be retrieved by CI tooling, Engineers can reference the role and possibly a per project specific role can be created if necessary.

### Value / Purpose

The SSM Parameter key is created by the ci-pipeline-webhook module in a very specific format for each project.
This no longer exists for projects such as "staff-device-private-dns-zone" as CodeBuild has been deleted and it's using the new GitHub Actions CI method.
This has blocked an update to the documentation and make file update for above project 
https://app.zenhub.com/workspaces/nvvs-devops-622a0b371800e400133bb924/issues/gh/ministryofjustice/staff-device-private-dns-zone/39

### Definition of Done

Example - [ ] Documentation has been written / updated
- [x] README has been updated
- [x] User docs have been updated
- [ ] Another team member has reviewed
- [x] Tests are green

**Comment by smjmoj** [comment]
Tested and applied PR outstanding for merge to main branch
https://github.com/ministryofjustice/staff-device-shared-services-infrastructure/pulls

**Comment by tomwells98** [comment]
Linked to ticket 39
